version: "3.9"
services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus-container
    ports:
      - "7777:8080"
    volumes:
      - ./config:/config
      - ./data:/data/
